# visual settings
DRAW = True

BG_COLOR = '#575757'
BOARD_COLOR = '#FFFFFF'
SNAKE_COLOR = '#00FF00'
APPLE_COLOR = "#FF0000"

BOARD_SIZE = 480
MARGIN_TOP = 10
MARGIN_SIDES = 60
MARGIN_DOWN = 100

BOARD_LEFT = MARGIN_SIDES
BOARD_TOP = MARGIN_TOP
BOARD_RIGHT = MARGIN_SIDES + BOARD_SIZE
BOARD_DOWN = MARGIN_TOP + BOARD_SIZE


# genetic settings
POPULATION = 100
MUTATION_CHANCE = 0.10
BEST_N = 5


# game settings
SPEED = 3
RADIUS = 15


# nn settings
NETWORK = [24, 20, 12, 4]
